### ISSUE TITLE
Tela de login

### ISSUE THREAD

**Issue by elton-fonseca** [elton-fonseca/levaai-app#1]
na tela de login em resolução pequena a última linha ficou muito próximo do fim, subir um pouquinho.

E colocar link no **clique aqui**

![WhatsApp Image 2020-10-02 at 16 31 56](https://user-images.githubusercontent.com/3722700/95900969-06b22f00-0d69-11eb-8684-adb2dfe638de.jpeg)

**Comment by wesleygado** [comment]
Feito
