### ISSUE TITLE
tela de recuperar a senha

### ISSUE THREAD

**Issue by elton-fonseca** [elton-fonseca/levaai-app#4]
Vou usar a mesma tela para recuperar e trocar a senha. Primeiro o cara vai informar celular de cadastro dele, então vou mandar um sms com código de validação que ele deve inserir. Precisamos criar 2 telas, mais ou menos assim:

![esqueci-a-senha](https://user-images.githubusercontent.com/3722700/95905503-54ca3100-0d6f-11eb-85d2-ba7335d3cc08.png)

Pode usar o estilo azul da tela de login com os mesmos estilo de campos e botão. Na primeira tela tem o campo para digitar o telefone de cadastro e clicar em próximo. Na segunda tela, tem o código de confirmação, senha e confirmação de senha.

acho que nas duas telas pode usar ícones grandes como fez na confirmação do financeiro para dar um estilo.

**Comment by wesleygado** [comment]
Feito
